services:
  web:
    build: .
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: yt
      MYSQL_USER: alex
      MYSQL_PASSWORD: azerty
    ports:
      - "2206:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
